name: Java CI with Maven & Docker Push

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        run: echo "Vikram@70" | docker login -u "vikramdip40@gmail.com" --password-stdin

      - name: Build Docker image
        run: docker build -t vikramjoshi123/spring-ci-cd-test:latest -f Dockerfile .

      - name: Push Docker image
        run: |
          docker tag vikramjoshi123/spring-ci-cd-test:latest vikramjoshi123/spring-ci-cd-test:v1
          docker push vikramjoshi123/spring-ci-cd-test:latest
          docker push vikramjoshi123/spring-ci-cd-test:v1
